imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

swiftmailer:
    disable_delivery: true

knp_rad:
    mailer:
        logger: true
    listener:
        exception_rethrow: true

web_profiler:
    toolbar: false
    intercept_redirects: false
