services:
    reactifony.test.block.service.text_block_service:
        class: Reactifony\TestBundle\Block\Service\TextBlockService
        tags:
            - { name: reactifony.block.service }

    reactifony.test.block.service.documents_block_service:
        class: Reactifony\TestBundle\Block\Service\DocumentsBlockService
        tags:
            - { name: reactifony.block.service }

    reactifony.test.block.service.accordion_block_service:
        class: Reactifony\TestBundle\Block\Service\AccordionBlockService
        tags:
            - { name: reactifony.block.service }
